
# Facebook Registration lane
CreateNewAccount = "/html[1]/body[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[5]/a[1]"
Registration_Page = "//div[contains(text(),'Sign Up')]"
FirstName_Element = "firstname"
LastName_Element = "lastname"
EmailInput_Element = "reg_email__"
Email_Reenter_Element = "reg_email_confirmation__"
Password_Element = "reg_passwd__"
BirthDay_Element = "//select[@id='day']"
BirthMonth_Element = "//select[@id='month']"
BirthYear_Element = "//select[@id='year']"
GenderSelect_Element = "/html[1]/body[1]/div[3]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/div[1]/div[7]/span[1]/span[2]/input[1]"
SignUp_Button = "/html[1]/body[1]/div[3]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/div[1]/div[11]/button[1]"
Email_Confirmation = "/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/h2[1]"
Continue_Button = "/html[1]/body[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/form[1]/div[2]/div[1]/button[1]"
Ok_Button = "//a[contains(text(),'OK')]"
null_All_spaces= "/html[1]/body[1]/div[7]/div[1]/div[1]/div[1]"
Error_InvalidEmail = "/html[1]/body[1]/div[7]/div[1]/div[1]/div[1]"
Error_nullGender = "/html[1]/body[1]/div[7]/div[1]/div[1]/div[1]"
Error_nullFirstName = "/html[1]/body[1]/div[7]/div[1]/div[1]/div[1]"
Error_nullLastName = "/html[1]/body[1]/div[7]/div[1]/div[1]/div[1]"
Error_Birthday = "/html[1]/body[1]/div[7]/div[1]/div[1]/div[1]"